music/urls.py
from django.urls import path
app_name = 'music'

from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('<int:album_id>/', views.detail, name = 'detail'),

    # /music/album_id/favourite/
    path('<int:album_id>/favourite/',views.favourite, name = 'favourite'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
]

music/models.py
from django.db import models
from django.contrib.auth.models import Group

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + '-' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default = False)

    def __str__(self):
        return self.song_title

music/views.py
from django.http import Http404
from .models import Album, Song
from django.shortcuts import render, get_object_or_404

def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums' : all_albums})


def detail(request,album_id):
    """
    try:
        album = Album.objects.get(pk = album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exist")
    """
    album = get_object_or_404(Album, pk = album_id)
    return render(request, 'music/detail.html',{'album':album})



def favourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album':album,
            'error_message': "You did not select a valid song",
        })
    else:
        selected_song.is_favourite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<img src = "{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

<!--
<ul>
    {% for song in album.song_set.all %}
    <li>{{ song.song_title }} - {{ song.file_type }}</li>
    {% endfor %}
</ul>
-->
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action ="{% url 'music:favourite' album_id=album.id %}" method = "post">
    {% csrf_token %}
    {% for song in album.song_set.all %}

        <label for="song{{ forloop.counter }}">
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">

            {{ song.song_title }}

            {% if song.is_favourite %}
                 <img src="https://www.iconspng.com/images/red-heart-icon/red-heart-icon.jpg" height="20" width="20">
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit"  value="Favourite">
    <input type="submit"  value="Dislike">
</form>

music/templates/music/index.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>

<ul>
    <h3> Hera are all my Albums</h3>
    {% for album in all_albums %}
    <li> <a href = "{% url 'music:detail' album_id=album.id %}">{{album.artist}}</a> </li>
    {% endfor %}
</ul>